## Carga de las Rutas.
## Ruta default
app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

app_usuario:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix: /usuario