BackendBundle\Entity\TblAsistencia:
    type: entity
    table: tbl_asistencia
    indexes:
        fk_tbl_asistencia_1_idx:
            columns:
                - id_alumno
        fk_tbl_asistencia_2_idx:
            columns:
                - id_clase
        fk_tbl_asistencia_3_idx:
            columns:
                - id_plato
    id:
        idAsistencia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_asistencia
            generator:
                strategy: IDENTITY
    fields:
        codAsistencia:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: cod_asistencia
        fechaAsistencia:
            type: date
            nullable: true
            column: fecha_asistencia
        horaAsistencia:
            type: datetime
            nullable: true
            column: hora_asistencia
        asistioClase:
            type: boolean
            nullable: true
            column: asistio_clase
        observaciones:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
        notaPlato:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: nota_plato
    manyToOne:
        idAlumno:
            targetEntity: TblAlumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_alumno:
                    referencedColumnName: id_alumno
            orphanRemoval: false
        idClase:
            targetEntity: TblClase
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_clase:
                    referencedColumnName: id_clase
            orphanRemoval: false
        idPlato:
            targetEntity: TblPlato
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_plato:
                    referencedColumnName: id_plato
            orphanRemoval: false
    lifecycleCallbacks: {  }
