BackendBundle\Entity\TblEvaluacionCortePrecision:
    type: entity
    table: tbl_evaluacion_corte_precision
    indexes:
        fk_tbl_evaluacion_corte_precision_1_idx:
            columns:
                - id_plato
        fk_tbl_evaluacion_corte_precision_2_idx:
            columns:
                - id_instructor
        fk_tbl_evaluacion_corte_precision_3_idx:
            columns:
                - id_alumno
        fk_3_idx:
            columns:
                - id_estado
    id:
        idEvaluacionCortePrecision:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_evaluacion_corte_precision
            generator:
                strategy: IDENTITY
    fields:
        codEvaluacionCortePrecision:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: cod_evaluacion_corte_precision
        higieneGeneralObs:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: higiene_general_obs
        higieneGeneralNota:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: higiene_general_nota
        limpiezaObs:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: limpieza_obs
        limpiezaNota:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: limpieza_nota
        uniformeCompletoObs:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: uniforme_completo_obs
        uniformeCompletoNota:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: uniforme_completo_nota
        filoCuchilloObs:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: filo_cuchillo_obs
        filoCuchilloNota:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: filo_cuchillo_nota
        tecnicaCuchilloObs:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: tecnica_cuchillo_obs
        tecnicaCuchilloNota:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: tecnica_cuchillo_nota
        pesoCorteObs:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: peso_corte_obs
        pesoCorteNota:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: peso_corte_nota
        fechaEvaluacion:
            type: date
            nullable: true
            column: fecha_evaluacion
        horaEvaluacion:
            type: datetime
            nullable: true
            column: hora_evaluacion
        notaFinal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: nota_final
        medidasCortesObs:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: medidas_cortes_obs
        medidasCortesNota:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: medidas_cortes_nota
        chefNotaFinalObs:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: chef_nota_final_obs
    manyToOne:
        idEstado:
            targetEntity: TblEstado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
        idPlato:
            targetEntity: TblPlato
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_plato:
                    referencedColumnName: id_plato
            orphanRemoval: false
        idInstructor:
            targetEntity: TblUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_instructor:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        idAlumno:
            targetEntity: TblAlumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_alumno:
                    referencedColumnName: id_alumno
            orphanRemoval: false
    lifecycleCallbacks: {  }
