BackendBundle\Entity\TblGenero:
    type: entity
    table: tbl_genero
    id:
        idGenero:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_genero
            generator:
                strategy: IDENTITY
    fields:
        codGenero:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: cod_genero
        descripcionGenero:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: descripcion_genero
    lifecycleCallbacks: {  }
