BackendBundle\Entity\TblGrupo:
    type: entity
    table: tbl_grupo
    id:
        idGrupos:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_grupos
            generator:
                strategy: IDENTITY
    fields:
        codGrupo:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: cod_grupo
        descGrupo:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: desc_grupo
    lifecycleCallbacks: {  }
