BackendBundle\Entity\TblMedioConoceAch:
    type: entity
    table: tbl_medio_conoce_ach
    id:
        idMedioConoceAch:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_medio_conoce_ach
            generator:
                strategy: IDENTITY
    fields:
        codMedioConoceAch:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: cod_medio_conoce_ach
        descripcionMedioConoceAch:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: descripcion_medio_conoce_ach
    lifecycleCallbacks: {  }
