BackendBundle\Entity\TblLugarPractica:
    type: entity
    table: tbl_lugar_practica
    id:
        idLugarPractica:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_lugar_practica
            generator:
                strategy: IDENTITY
    fields:
        codLugarPractica:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: cod_lugar_practica
        descLugarPractica:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: desc_lugar_practica
    lifecycleCallbacks: {  }
