BackendBundle\Entity\TblPago:
    type: entity
    table: tbl_pago
    indexes:
        fk_tbl_pago_1_idx:
            columns:
                - id_estado_pago
        fk_tbl_pago_2_idx:
            columns:
                - id_alumno
        fk_tbl_pago_3_idx:
            columns:
                - id_forma_pago
        fk_tbl_pago_4_idx:
            columns:
                - id_tipo_pago
        fk_tbl_pago_5_idx:
            columns:
                - id_usuario
    id:
        idPago:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_pago
            generator:
                strategy: IDENTITY
    fields:
        codDocumento:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: cod_documento
        fechaPago:
            type: date
            nullable: true
            column: fecha_pago
        horaPago:
            type: datetime
            nullable: true
            column: hora_pago
        conceptoPago:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: concepto_pago
        montoPago:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: monto_pago
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
        horaModificacion:
            type: datetime
            nullable: true
            column: hora_modificacion
        descripcionPago:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: descripcion_pago
    manyToOne:
        idEstadoPago:
            targetEntity: TblEstado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado_pago:
                    referencedColumnName: id_estado
            orphanRemoval: false
        idAlumno:
            targetEntity: TblAlumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_alumno:
                    referencedColumnName: id_alumno
            orphanRemoval: false
        idFormaPago:
            targetEntity: TblFormaPago
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_forma_pago:
                    referencedColumnName: id_forma_pago
            orphanRemoval: false
        idTipoPago:
            targetEntity: TblTipoPago
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_pago:
                    referencedColumnName: id_tipo_pago
            orphanRemoval: false
        idUsuario:
            targetEntity: TblUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
