BackendBundle\Entity\TblTipoPago:
    type: entity
    table: tbl_tipo_pago
    id:
        idTipoPago:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_pago
            generator:
                strategy: IDENTITY
    fields:
        codTipoPago:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: cod_tipo_pago
        descTipoPago:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: desc_tipo_pago
        activo:
            type: boolean
            nullable: true
            options:
                default: '1'
    lifecycleCallbacks: {  }
