BackendBundle\Entity\TblTipoBeca:
    type: entity
    table: tbl_tipo_beca
    id:
        idTipoBeca:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_beca
            generator:
                strategy: IDENTITY
    fields:
        codTipoBeca:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: cod_tipo_beca
        descTipoBeca:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: desc_tipo_beca
    lifecycleCallbacks: {  }
