BackendBundle\Entity\TblUsuario:
    type: entity
    table: tbl_usuario
    indexes:
        cod_usuario:
            columns:
                - cod_usuario
        fk_tbl_usuarios_1_idx:
            columns:
                - id_tipo_usuario
        fk_tbl_usuarios_2_idx:
            columns:
                - id_estado
    id:
        idUsuario:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_usuario
            generator:
                strategy: IDENTITY
    fields:
        codUsuario:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: cod_usuario
        nombre1:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        nombre2:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        apellido1:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        apellido2:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        telefono:
            type: integer
            nullable: true
            options:
                unsigned: false
        celular:
            type: integer
            nullable: false
            options:
                unsigned: false
        password:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        fechaCreacion:
            type: date
            nullable: true
            column: fecha_creacion
        horaCreacion:
            type: datetime
            nullable: true
            column: hora_creacion
        activo:
            type: boolean
            nullable: true
        iniciales:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        urlImagen:
            type: string
            nullable: false
            length: 300
            options:
                fixed: false
            column: url_imagen
    manyToOne:
        idTipoUsuario:
            targetEntity: TblTipoUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_usuario:
                    referencedColumnName: id_tipo_usuario
            orphanRemoval: false
        idEstado:
            targetEntity: TblEstado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
    lifecycleCallbacks: {  }
