BackendBundle\Entity\TblEvaluacion:
    type: entity
    table: tbl_evaluacion
    indexes:
        fk_tbl_evaluacion_1_idx:
            columns:
                - id_alumno
        fk_tbl_evaluacion_2_idx:
            columns:
                - id_instructor
    id:
        idEvaluacion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_evaluacion
            generator:
                strategy: IDENTITY
    fields:
        codEvaluacion:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: cod_evaluacion
        fechaEvaluacion:
            type: date
            nullable: true
            column: fecha_evaluacion
        horaEvaluacion:
            type: datetime
            nullable: true
            column: hora_evaluacion
        observaciones:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
    manyToOne:
        idAlumno:
            targetEntity: TblAlumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_alumno:
                    referencedColumnName: id_alumno
            orphanRemoval: false
        idInstructor:
            targetEntity: TblInstructor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_instructor:
                    referencedColumnName: id_instructor
            orphanRemoval: false
    lifecycleCallbacks: {  }
