BackendBundle\Entity\TblExamen:
    type: entity
    table: tbl_examen
    indexes:
        fk_new_table_1_idx:
            columns:
                - id_alumno
        fk_new_table_2_idx:
            columns:
                - id_instructor
        fk_new_table_3_idx:
            columns:
                - id_clase
    id:
        idExamen:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_examen
            generator:
                strategy: IDENTITY
    fields:
        codExamen:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: cod_examen
        notaExamen:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
            column: nota_examen
    manyToOne:
        idAlumno:
            targetEntity: TblAlumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_alumno:
                    referencedColumnName: id_alumno
            orphanRemoval: false
        idInstructor:
            targetEntity: TblInstructor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_instructor:
                    referencedColumnName: id_instructor
            orphanRemoval: false
        idClase:
            targetEntity: TblClase
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_clase:
                    referencedColumnName: id_clase
            orphanRemoval: false
    lifecycleCallbacks: {  }
