BackendBundle\Entity\TblTipoClase:
    type: entity
    table: tbl_tipo_clase
    id:
        idTipoClase:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_clase
            generator:
                strategy: IDENTITY
    fields:
        codTipoClase:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: cod_tipo_clase
        descripcionTipoClase:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: descripcion_tipo_clase
    lifecycleCallbacks: {  }
