BackendBundle\Entity\TblTipoEvaluacion:
    type: entity
    table: tbl_tipo_evaluacion
    id:
        idTipoEvaluacion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_evaluacion
            generator:
                strategy: IDENTITY
    fields:
        codTipoEvaluacion:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: cod_tipo_evaluacion
        nombreTipoEvaluacion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nombre_tipo_evaluacion
    lifecycleCallbacks: {  }
