BackendBundle\Entity\TblClaseAlumno:
    type: entity
    table: tbl_clase_alumno
    id:
        idClaseAlumno:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_clase_alumno
            generator:
                strategy: IDENTITY
    fields:
        idClase:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_clase
        idAlumno:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_alumno
    lifecycleCallbacks: {  }
