BackendBundle\Entity\TblDocumentoInasistencia:
    type: entity
    table: tbl_documento_inasistencia
    indexes:
        fk_tbl_documentos_inasistencias_1_idx:
            columns:
                - id_justificacion_inasistencia
    id:
        idDocumentosInasistencias:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_documentos_inasistencias
            generator:
                strategy: IDENTITY
    fields:
        urlDocumento:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: url_documento
    manyToOne:
        idJustificacionInasistencia:
            targetEntity: TblJustificacionInasistencia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_justificacion_inasistencia:
                    referencedColumnName: id_justificacion_inasistencia
            orphanRemoval: false
    lifecycleCallbacks: {  }
