BackendBundle\Entity\TblInstructor:
    type: entity
    table: tbl_instructor
    id:
        idInstructor:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_instructor
            generator:
                strategy: IDENTITY
    fields:
        codInstructor:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: cod_instructor
        nombre1:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        nombre2:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        apellido1:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        apellido2:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
        aniosExp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: anios_exp
        lugarEgresado:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: lugar_egresado
    lifecycleCallbacks: {  }
