BackendBundle\Entity\TblSecuenciales:
    type: entity
    table: tbl_secuenciales
    id:
        idSecuencia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_secuencia
            generator:
                strategy: IDENTITY
    fields:
        codSecuencia:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: cod_secuencia
        valor1:
            type: integer
            nullable: true
            options:
                unsigned: false
        valor2:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
