BackendBundle\Entity\TblTipoPlato:
    type: entity
    table: tbl_tipo_plato
    id:
        idTipoPlato:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_plato
            generator:
                strategy: IDENTITY
    fields:
        codTipoPlato:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: cod_tipo_plato
        descripcionTipoPlato:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: descripcion_tipo_plato
        activo:
            type: boolean
            nullable: true
            options:
                default: '1'
    lifecycleCallbacks: {  }
