## Rutas Alumno.
alumno_listAllAlumno:
    path: /all-list-alumnos
    defaults: { _controller: "AppBundle:Alumno/Alumno:ActiveAllAlumnoList" }
    methods: GET

## Ruta para Agregar Nuevo Alumno
alumno_newAlumno:
    path: /new-alumno
    defaults: { _controller: "AppBundle:Alumno/Alumno:NewAlumno" }
    methods: POST

## Ruta para Editar Alumno
alumno_editAlumno:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST