## Rutas de Usuario.
usuario_new:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: POST
    
usuario_update:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: POST

## Ruta para el Login
usuario_delete:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: GET