## Rutas Pago Alumno.
pagos_listAllPagoAlumno:
    path: /all-list-pagos
    defaults: { _controller: "AppBundle:Pagos/Pagos:ActiveAllPagosList" }
    methods: POST

## Ruta para Agregar Nuevo Pago de Alumno
pagos_newAlumnoPago:
    path: /new-pago-alumno
    defaults: { _controller: "AppBundle:Pagos/Pagos:NewPagoAlumno" }
    methods: POST
    
## Ruta para Anualar Nuevo Pago de Alumno
pagos_revertAlumnoPago:
    path: /revert-pago-alumno
    defaults: { _controller: "AppBundle:Pagos/Pagos:RevertPagoAlumno" }
    methods: POST

## Ruta para listar todos los Pagos realizafos por el Alumno
pagos_listPagosAlumno:
    path: /all-list-alumno-pagos
    defaults: { _controller: "AppBundle:Pagos/Pagos:ActiveAllAlumnoPagosList" }
    methods: POST
    
## Ruta para cargar el documento de Pago
pagos_uploadDocPago:
    path: /upload-doc-pago
    defaults: { _controller: "AppBundle:Pagos/Pagos:UploadDocumentoPago" }
    methods: POST